UPdate workflox

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -173,13 +173,27 @@ jobs:
 
           # Deploy
           ssh $SSH_USER@$SSH_HOST << 'EOF'
+            set -e  # Fail immediate if any command fails
+            set -x  # Print commands
+            
             cd /opt/suprennes
             
+            echo "Current directory content:"
+            ls -la
+
+            echo "Checking Docker version:"
+            docker compose version || docker-compose --version || echo "Docker Compose not found"
+
             # Pull new images
+            echo "Pulling images..."
             docker compose pull
             
             # Start/Restart services
+            echo "Starting services..."
             docker compose up -d --remove-orphans
+            
+            # Check if they are running
+            docker compose ps
             
             # Cleanup old images
             docker image prune -f
